services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lms
    volumes:
      - pg_data:/var/lib/postgresql
    networks:
      - backend

  api:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8081:8081
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  pg_data:
    driver: local
